'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class ClassRoom
    Public Property Id As Integer
    <Required>
    <StringLength(5)>
    <Display(Name:="Room number")>
    Public Property RoomNumber As String
    <Required>
    <StringLength(250)>
    <Display(Name:="Description")>
    Public Property Description As String

    Public Overridable Property Courses As ICollection(Of Cours) = New HashSet(Of Cours)

End Class
