'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CourseAttendency
    Public Property Id As Integer
    Public Property StudentId As Integer
    Public Property CourseId As Integer
    Public Property CheckinDate As Date
    Public Property CheckoutDate As Date

    Public Overridable Property Cours As Cours
    Public Overridable Property Student As Student

End Class
