'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class Cours
    Public Property Id As Integer
    <Required>
    <StringLength(50)>
    Public Property Name As String
    <StringLength(250)>
    Public Property Description As String
    <Required>
    <DataType(DataType.Time)>
    Public Property StartHour As Date
    <Required>
    <DataType(DataType.Time)>
    Public Property EndHour As Date
    <Required>
    <Display(Name:="Minimum Age")>
    Public Property MinimumAge As Integer
    <Required>
    <Display(Name:="Maximum Age")>
    Public Property MaximumAge As String
    <Required>
    <Display(Name:="Day Of Week")>
    Public Property DayOfWeek As String
    Public Property Status As Integer

    Public Overridable Property CourseAttendencies As ICollection(Of CourseAttendency) = New HashSet(Of CourseAttendency)
    Public Overridable Property ClassRooms As ICollection(Of ClassRoom) = New HashSet(Of ClassRoom)
    Public Overridable Property Teachers As ICollection(Of Teacher) = New HashSet(Of Teacher)

End Class
