'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Guardian
    Public Property Id As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Address As String
    Public Property City As String
    Public Property CellNumber As String
    Public Property HomeNumber As String
    Public Property Status As Integer

    Public Overridable Property GuardianStudents As ICollection(Of GuardianStudent) = New HashSet(Of GuardianStudent)

End Class
