'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class Guardian
    Public Property Id As Integer
    <Required>
    <StringLength(50)>
    <Display(Name:="First Name")>
    Public Property FirstName As String
    <Required>
    <StringLength(50)>
    <Display(Name:="Last Name")>
    Public Property LastName As String
    <Required>
    <StringLength(150)>
    Public Property Address As String
    <Required>
    <StringLength(50)>
    Public Property City As String
    <Required>
    <StringLength(13)>
    <Display(Name:="Cell Number")>
    Public Property CellNumber As String
    <Required>
    <StringLength(20)>
    <Display(Name:="Home Number")>
    Public Property HomeNumber As String
    Public Property Status As Integer

    Public Overridable Property GuardianStudents As ICollection(Of GuardianStudent) = New HashSet(Of GuardianStudent)

End Class
