'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GuardianStudent
    Public Property GuardianId As Integer
    Public Property StudentId As Integer
    Public Property GuardianTypeId As Integer

    Public Overridable Property Guardian As Guardian
    Public Overridable Property GuardianType As GuardianType
    Public Overridable Property Student As Student

End Class
