'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class Student
    Public Property Id As Integer
    <Required>
    <StringLength(50)>
    <Display(Name:="First Name")>
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Address As String
    Public Property City As String
    <Required>
    <DataType(DataType.Date)>
    <Display(Name:="Date of Birth")>
    Public Property DateBirth As Date
    Public Property Allergies As String
    <Required>
    <StringLength(500)>
    <Display(Name:="Special Instructions")>
    Public Property SpecialInstructions As String
    Public Property CourseId As Nullable(Of Integer)

    Public Overridable Property CourseAttendencies As ICollection(Of CourseAttendency) = New HashSet(Of CourseAttendency)
    Public Overridable Property GuardianStudents As ICollection(Of GuardianStudent) = New HashSet(Of GuardianStudent)
    Public Overridable Property Cours As Cours

End Class
