'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SundaySchoolRegistryContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SundaySchoolRegistryContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ClassRooms() As DbSet(Of ClassRoom)
    Public Overridable Property CourseAttendencies() As DbSet(Of CourseAttendency)
    Public Overridable Property Courses() As DbSet(Of Cours)
    Public Overridable Property Guardians() As DbSet(Of Guardian)
    Public Overridable Property GuardianStudents() As DbSet(Of GuardianStudent)
    Public Overridable Property GuardianTypes() As DbSet(Of GuardianType)
    Public Overridable Property Students() As DbSet(Of Student)
    Public Overridable Property Teachers() As DbSet(Of Teacher)

End Class
